### ISSUE TITLE
Add design system

### ISSUE THREAD

**Issue by gabbijonsson** [jonssons-io/ag-budget#5]
```[tasklist]
### Tasks
- [x] Add ant design
- [x] Configure theme
- [x] Add dark mode switch with storage of preference
- [x] Check users browser default for darkmode
```
